server:
  port: 8084

spring:
  application:
    name: chat-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kawach_chat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true
